### ISSUE TITLE
运行直接抱错，请问需要怎么处理呢

### ISSUE THREAD

**Issue by hekejian** [wuhan2020/rest-api#1]
import { Object as LCObject, Query, ACL } from 'leanengine';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by TechQuery** [comment]
Mac OS X 容易出现 [ts-node][1] *运行时不编译*的 bug，你先把前端代码里的 `localhost:3000` 改成 `vsw505fxbitp.leanapp.cn` 直连测试服务器吧

[1]: https://github.com/TypeStrong/ts-node

**Comment by hekejian** [comment]
done

**Comment by hekejian** [comment]
get

**Comment by Marla62** [comment]
同样遇到此问题
